<?php

namespace Rainmaker\Process;

use Symfony\Component\Process\Process;

/**
 * A wrapper class for executing processes.
 *
 * @package Rainmaker\Process
 * @return void
 */
class ProcessRunner {

  /**
   * Runs a process and returns the output.
   *
   * @param Process $process
   * @return string
   */
  public function run(Process $process, $returnOutput = true)
  {
    $process->mustRun();
    if ($returnOutput) {
      return $this->getProcessOutput($process);
    }
  }

  /**
   * Gets the output generated by running the given process.
   *
   * @param Process $process
   * @return string
   */
  public function getProcessOutput(Process $process)
  {
    return $process->getOutput();
  }

}
